import Head from "next/head";

import { Navbar } from "@/components/Navbar";
import { Header } from "@/components/Header";
import { University } from "@/components/University";
import { Current } from "@/components/Current";
import { News } from "@/components/News";
import { Goto } from "@/components/Goto";
import { Footer } from "@/components/Footer";
import { FeedBack } from "@/components/FeedBack";

export default function Home() {
  return (
    <>
      <Head>
        <title>University of amsterdam</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Navbar />
        <Header />
        <University />
        <Current />
        <News />
        <Goto />
        <Footer />
        <FeedBack />
      </>
    </>
  );
}
